// Generated by gencpp from file motor_cam_tutorial/image_cmd.msg
// DO NOT EDIT!


#ifndef MOTOR_CAM_TUTORIAL_MESSAGE_IMAGE_CMD_H
#define MOTOR_CAM_TUTORIAL_MESSAGE_IMAGE_CMD_H

#include <ros/service_traits.h>


#include <motor_cam_tutorial/image_cmdRequest.h>
#include <motor_cam_tutorial/image_cmdResponse.h>


namespace motor_cam_tutorial
{

struct image_cmd
{

typedef image_cmdRequest Request;
typedef image_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct image_cmd
} // namespace motor_cam_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_cam_tutorial::image_cmd > {
  static const char* value()
  {
    return "7d1acd9e38bea5a59992565b097ec10a";
  }

  static const char* value(const ::motor_cam_tutorial::image_cmd&) { return value(); }
};

template<>
struct DataType< ::motor_cam_tutorial::image_cmd > {
  static const char* value()
  {
    return "motor_cam_tutorial/image_cmd";
  }

  static const char* value(const ::motor_cam_tutorial::image_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::motor_cam_tutorial::image_cmdRequest> should match 
// service_traits::MD5Sum< ::motor_cam_tutorial::image_cmd > 
template<>
struct MD5Sum< ::motor_cam_tutorial::image_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_cam_tutorial::image_cmd >::value();
  }
  static const char* value(const ::motor_cam_tutorial::image_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_cam_tutorial::image_cmdRequest> should match 
// service_traits::DataType< ::motor_cam_tutorial::image_cmd > 
template<>
struct DataType< ::motor_cam_tutorial::image_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::motor_cam_tutorial::image_cmd >::value();
  }
  static const char* value(const ::motor_cam_tutorial::image_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_cam_tutorial::image_cmdResponse> should match 
// service_traits::MD5Sum< ::motor_cam_tutorial::image_cmd > 
template<>
struct MD5Sum< ::motor_cam_tutorial::image_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_cam_tutorial::image_cmd >::value();
  }
  static const char* value(const ::motor_cam_tutorial::image_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_cam_tutorial::image_cmdResponse> should match 
// service_traits::DataType< ::motor_cam_tutorial::image_cmd > 
template<>
struct DataType< ::motor_cam_tutorial::image_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::motor_cam_tutorial::image_cmd >::value();
  }
  static const char* value(const ::motor_cam_tutorial::image_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_CAM_TUTORIAL_MESSAGE_IMAGE_CMD_H
